# Copyright (c) 2022-2025, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

from .pressure_taxel_map import (
    CalibratedPressureMapSensor,
    PenetrationFrame,
    PressureCalibration,
    PressureContactEventBatch,
    PressureFrame,
    PressureMapOutput,
    PressureTaxelMap,
    TaxelLayout,
    UrdfPressureContactAdapter,
    calibrate_force,
    calibrate_gap_fraction,
    calibrate_penetration,
    coerce_taxel_calibration_value,
    empty_contact_events,
    pressure_map_stats,
    spread_contact_events_to_taxels,
)
from .pressure_calibration_io import (
    load_pressure_calibration_overrides,
    pressure_calibration_value_summary,
)
from .pressure_l0_benchmark import (
    AnalyticPressTrajectory,
    AnalyticPresserSpec,
    L0PressureTrace,
    analytic_presser_penetration,
    generate_l0_pressure_trace,
)
from .pressure_geometry_alignment import (
    align_reference_to_pressure_taxels,
    aligned_reference_points_for_pressure_taxels,
    apply_reference_alignment_to_values,
    build_reference_to_pressure_alignment,
    write_geometry_aligned_trace,
)
from .pressure_normal_ray_trace import (
    apply_normal_ray_reference_to_trace,
    write_normal_ray_reference_trace,
)
from .pressure_geometry_normal_ray_trace import (
    apply_geometry_normal_ray_to_trace,
    write_geometry_normal_ray_trace,
)
from .pressure_reference_calibration import (
    PressureDeadbandFitConfig,
    PressureAreaFractionFitConfig,
    PressureMaskDepthFitConfig,
    PressureSampleSupportFitConfig,
    PressureSpatialFootprintFitConfig,
    apply_pressure_area_fraction_to_trace,
    apply_pressure_deadband_to_trace,
    apply_pressure_mask_depth_to_trace,
    apply_pressure_sample_support_to_trace,
    apply_pressure_spatial_footprint_to_trace,
    fit_pressure_area_fraction_to_reference,
    fit_pressure_deadband_to_reference,
    fit_pressure_mask_depth_to_reference,
    fit_pressure_sample_support_to_reference,
    fit_pressure_spatial_footprint_to_reference,
    write_area_fraction_fit_trace,
    write_deadband_fit_trace,
    write_mask_depth_fit_trace,
    write_sample_support_fit_trace,
    write_spatial_footprint_fit_trace,
)
from .pressure_sources import (
    GeometryNormalRayPenetrationSource,
    NormalRayPenetrationSource,
    PhysxContactSource,
    SampledPenetrationStats,
    UrdfPressureLayoutSource,
    WarpSdfPenetrationSource,
    triangle_mesh_topology_diagnostics,
    weld_duplicate_triangle_vertices,
)
from .pressure_trace_metrics import (
    DENSE_REFERENCE_ACCEPTANCE_LAYERS,
    UNSAFE_REFERENCE_OVERRIDE_LAYERS,
    evaluate_pressure_trace_report,
    infer_pressure_reference_layer,
    load_pressure_trace_npz,
    pressure_reference_frame_diagnostics,
    pressure_reference_origin_alignment_diagnostics,
    pressure_sample_boundary_diagnostics,
    pressure_trace_report,
    reference_mask_metrics,
    validate_pressure_trace_v1,
)
from .urdf_pressure_layout import (
    UrdfPressurePadSpec,
    load_pressure_pad_specs_from_urdf,
    load_pressure_taxel_maps_from_urdf,
    load_pressure_touch_links_from_urdf,
    load_touch_links_from_urdf,
    select_pressure_pad_spec,
)

try:
    from .warp_sdf_tactile_cfg import WarpSdfTactileSensorCfg
    from .warp_sdf_tactile_sensor import WarpSdfTactileSensor
except ModuleNotFoundError as exc:  # pragma: no cover - only used outside Isaac Lab runtimes
    if exc.name not in {"isaaclab", "warp", "omni", "pxr"}:
        raise
    WarpSdfTactileSensorCfg = None
    WarpSdfTactileSensor = None

__all__ = [
    "AnalyticPressTrajectory",
    "AnalyticPresserSpec",
    "CalibratedPressureMapSensor",
    "DENSE_REFERENCE_ACCEPTANCE_LAYERS",
    "GeometryNormalRayPenetrationSource",
    "L0PressureTrace",
    "NormalRayPenetrationSource",
    "PenetrationFrame",
    "PressureCalibration",
    "PressureAreaFractionFitConfig",
    "PressureDeadbandFitConfig",
    "PressureContactEventBatch",
    "PressureFrame",
    "PressureMaskDepthFitConfig",
    "PressureSampleSupportFitConfig",
    "PressureSpatialFootprintFitConfig",
    "PressureMapOutput",
    "PressureTaxelMap",
    "SampledPenetrationStats",
    "WarpSdfPenetrationSource",
    "UrdfPressureLayoutSource",
    "PhysxContactSource",
    "TaxelLayout",
    "triangle_mesh_topology_diagnostics",
    "weld_duplicate_triangle_vertices",
    "UrdfPressurePadSpec",
    "UrdfPressureContactAdapter",
    "UNSAFE_REFERENCE_OVERRIDE_LAYERS",
    "WarpSdfTactileSensor",
    "WarpSdfTactileSensorCfg",
    "align_reference_to_pressure_taxels",
    "aligned_reference_points_for_pressure_taxels",
    "analytic_presser_penetration",
    "apply_pressure_area_fraction_to_trace",
    "apply_geometry_normal_ray_to_trace",
    "apply_pressure_mask_depth_to_trace",
    "apply_pressure_sample_support_to_trace",
    "apply_pressure_spatial_footprint_to_trace",
    "apply_normal_ray_reference_to_trace",
    "apply_reference_alignment_to_values",
    "build_reference_to_pressure_alignment",
    "calibrate_force",
    "calibrate_gap_fraction",
    "calibrate_penetration",
    "coerce_taxel_calibration_value",
    "empty_contact_events",
    "evaluate_pressure_trace_report",
    "write_area_fraction_fit_trace",
    "write_deadband_fit_trace",
    "write_mask_depth_fit_trace",
    "write_sample_support_fit_trace",
    "write_spatial_footprint_fit_trace",
    "write_geometry_aligned_trace",
    "write_geometry_normal_ray_trace",
    "write_normal_ray_reference_trace",
    "fit_pressure_area_fraction_to_reference",
    "fit_pressure_deadband_to_reference",
    "fit_pressure_mask_depth_to_reference",
    "fit_pressure_sample_support_to_reference",
    "fit_pressure_spatial_footprint_to_reference",
    "apply_pressure_deadband_to_trace",
    "load_pressure_calibration_overrides",
    "load_pressure_pad_specs_from_urdf",
    "load_pressure_taxel_maps_from_urdf",
    "load_pressure_touch_links_from_urdf",
    "load_pressure_trace_npz",
    "load_touch_links_from_urdf",
    "select_pressure_pad_spec",
    "generate_l0_pressure_trace",
    "infer_pressure_reference_layer",
    "pressure_calibration_value_summary",
    "pressure_map_stats",
    "pressure_reference_frame_diagnostics",
    "pressure_reference_origin_alignment_diagnostics",
    "pressure_sample_boundary_diagnostics",
    "pressure_trace_report",
    "reference_mask_metrics",
    "spread_contact_events_to_taxels",
    "validate_pressure_trace_v1",
]
