[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "BrainCo Isaac Lab Tasks"
author = "BrainCo"
maintainer = "BrainCo"
description = "Public Isaac Lab environments and checkpoints for BrainCo Revo hands."
repository = ""
keywords = ["brainco", "isaaclab", "dexterous-manipulation", "reinforcement-learning", "revo"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_mimic" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}

[[python.module]]
name = "BrainCo_DexHand"

[isaaclab_settings]
